#!/bin/bash

cd "${0%/*}"

echo "Remounting / as read-write"
sudo mount -o remount,rw /

echo "Pulling new version"
sudo -u pi git pull

echo "Running install script"
bash ./install.sh

echo "Remounting / as read-only"
sudo mount -o remount,ro /

echo "Restarting service"
sudo systemctl restart bubbletube

